### ISSUE TITLE
Bug when parsing quoted string lists

### ISSUE THREAD

**Issue by khornel** [TynanSylvester/TyDSharp#4]
The ; list separator is only skipped when parsing non quoted strings, resulting in added null elements between quoted strings in a list.

**Comment by TynanSylvester** [comment]
Looks like it's more of a general bug. If there are repeated semicolons, they're parsed as a series of empty strings. I'm working on a fix.

**Comment by TynanSylvester** [comment]
Fixed now, thanks.
