### ISSUE TITLE
Reversed inheritance for string records

### ISSUE THREAD

**Issue by khornel** [TynanSylvester/TyDSharp#8]
If heir and source have matching string records, the heir will take the source's value, instead of doing nothing.
https://github.com/tyd-lang/TyDSharp/blob/28a03e842f782b2c7ea64c01c3866e3f6a3c3418/Inheritance.cs#L257

Example input:
```
TestParent *handle Base
{
    Value    Parent
    Table     { SubValue Parent }
}

TestChild *source Base
{
    Value     Child
    Table     { SubValue  Child }
}
```

Output using Inheritance.ResolveAll():
```
TestChild *source Base
{
	Value Parent
	Table
	{
		SubValue Parent
	}
}
```

**Comment by TynanSylvester** [comment]
What a foolish bug on my part.
I've made a test on my end to start catching more of these. Thanks for the clear report.
